baseURL: "https://namdar-nejad.github.io/" 
title: Namdar Nejad
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        # - name: Papers
        #   url: papers/
        #   weight: 2
        # - name: Courses
        #   url: courses/
        #   weight: 3
        # - name: Data
        #   url: data/
        #   weight: 4 
        # - name: Blog
        #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
        #   weight: 6

params:
    description: "This website hosts Nanmdar Nejad's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Namdar Nejad
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Namdar Nejad
          subtitle: "I'm a currently working as quant at Man Numeric, previously I studied CS and Math at McGill. In my free time I enjoy working on machine learning side projects and thinking about prediction markets. If you'd like to chat or connect, feel free to reach out or schedule a time below!"
          imageUrl: "website_pic.jpeg"
          imageWidth: 150
          imageHeight: 188
          buttons:
            # - name: Papers
            #   url: papers/
            # - name: Data
            #   url: data/
            # - name: Books
            #   url: books/
            # - name: Courses
            #   url: courses/
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/
            # - name: Blog
            #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        # - name: CV
        #   url: cv.pdf
        # - name: Zoom
        #   url: https://www.zoom.us/my/igelfeld
        # - name: Location
        #   url: location/
        # - name: Google Scholar
        #   url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        # - name: Twitter
        #   url: https://x.com/pmichaillat
        # - name: Bluesky
        #   url: https://bsky.app/profile/pmichaillat.bsky.social
        - name: Email
          url: mailto:namdar.nejad@mail.mcgill.ca
        - name: Office Hours
          url: https://calendly.com/namdar-kabolinejad-mail/15min
        - name: GitHub
          url: https://github.com/namdar-nejad
        - name: linkedin
          url: https://www.linkedin.com/in/namdar-nejad/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Namdar Nejad"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2